INSERT INTO price VALUES (1, 'USD', 23.4, 2)
INSERT INTO price VALUES (2, 'USD', 697.4, 5)
INSERT INTO price VALUES (3, 'USD', 1222.3, 1)
INSERT INTO price VALUES (4, 'USD', 10.3, 3)
INSERT INTO price VALUES (5, 'USD', 110.3, 4)
-- INSERT INTO price VALUES (6, currency, price, vehicle_id)
-- INSERT INTO price VALUES (7, currency, price, vehicle_id)
-- INSERT INTO price VALUES (id, currency, price, vehicle_id)
-- INSERT INTO price VALUES (id, currency, price, vehicle_id)
-- INSERT INTO price VALUES (id, currency, price, vehicle_id)
-- INSERT INTO price VALUES (id, currency, price, vehicle_id)
-- INSERT INTO price VALUES (id, currency, price, vehicle_id)
-- INSERT INTO price VALUES (id, currency, price, vehicle_id)
-- INSERT INTO price VALUES (id, currency, price, vehicle_id)
-- INSERT INTO price VALUES (id, currency, price, vehicle_id)
-- INSERT INTO price VALUES (id, currency, price, vehicle_id)
-- INSERT INTO price VALUES (id, currency, price, vehicle_id)
-- INSERT INTO price VALUES (id, currency, price, vehicle_id)
-- INSERT INTO price VALUES (id, currency, price, vehicle_id)
-- INSERT INTO price VALUES (id, currency, price, vehicle_id)